source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'rspec'
gem 'rack-test'
gem 'nokogiri', '1.6.0'
gem 'json', '1.8.0'
gem 'rest-client', '1.6.7'
gem 'watir-webdriver'
gem 'capybara'
gem 'capybara-webkit'
gem 'timecop'
gem 'sprockets'

